cache_path = ".cache/eth_sniper"
cache_ttl = 3600

[ethereum]
node_http = "http://172.16.111.204:8545"
node_ws = "ws://172.16.111.204:8546"

[block_explorer]
url = "https://etherscan.io"
api_key = "YourApiKeyToken"

[[dex.tokens]]
address = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
name = "WETH9"
symbol = "WETH"
decimals = 18

[[dex.routers]]
name = "uniswap"
version = "2"
factory = "0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f"
addresses = [
    # "0xf164fC0Ec4E93095b804a4795bBe1e041497b92a", # Deprecated v2 router
    "0x7a250d5630b4cf539739df2c5dacb4c659f2488d",
]

[[dex.routers]]
name = "uniswap"
version = "3"
factory = "0x1f98431c8ad98523631ae4a59f267346ea31f984"
addresses = [
    "0xe592427a0aece92de3edee1f18e0157c05861564",
    "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45",
]

[[dex.routers]]
name = "sushiswap"
version = "2"
factory = "0xc0aee478e3658e2610c5f7a4a2e1777ce9e4f2ac"
addresses = ["0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F"]

[nats]
url = "localhost"
subject_prefix = "eth_sniper"
queue_group = "eth_sniper"

[scylla]
url = "localhost"
keyspace = "eth_sniper"

[redis]
url = "redis://localhost:6379"
db = 0
# cluster = false
username = ""
password = ""

[log]
level = "debug"
